service: serverless-appsync-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: youtubeAppSyncApi
    authenticationType: AMAZON_COGNITO_USER_POOLS
    schema: # schema file or array of files to merge, defaults to schema.graphql (glob pattern is acceptable)
    userPoolConfig:
      awsRegion: us-east-1
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - type: Query
        field: getBookById
        dataSource: booksTable
      - type: Mutation
        field: createBook
        dataSource: booksTable
    dataSources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        description: "Dynamodb table for books"
        config:
          tableName: !Ref booksTable 

resources:
 Resources:
  ${file(resources.yml)}

