service: serverless-appsync-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1


resources:
 Resources:
  ${file(resources.yml)}

